app = ""
kill_signal = "SIGINT"
kill_timeout = "15s"

[build]
  dockerfile = "node.Dockerfile"

[experimental]
  auto_rollback = true

[env]
  CLOUD_PLATFORM = "fly"
  DENO_ENV = "production"
  LOG_LEVEL = "info"
  NODE_ENV = "production"

# DNS over HTTPS
[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true

  [[services.ports]]
    # TODO: ProxyProto v2
    port = 443
  [[services.ports]]
    port = 8080

  [services.concurrency]
    type = "connections"
    hard_limit = 575
    soft_limit = 500

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "3s"
    grace_period = "15s"
    restart_limit = 3

# DNS over TLS
[[services]]
  protocol = "tcp"
  internal_port = 10000
  auto_stop_machines = true
  auto_start_machines = true

  [[services.ports]]
    # TODO: ProxyProto v2
    port = 853
  [[services.ports]]
    port = 10000

  [services.concurrency]
    type = "connections"
    hard_limit = 575
    soft_limit = 500

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "3s"
    grace_period = "15s"
    restart_limit = 3

# community.fly.io/t/5490/3
[checks]
  [checks.up]
    # grace_period affects time taken for rolling deploys
    grace_period = "15s"
    interval = "15s"
    method = "get"
    path = "/check"
    port = 8888
    timeout = "3s"
    type = "http"
