app = ""

kill_signal = "SIGINT"
kill_timeout = "15s"

[build]
  dockerfile = "node.Dockerfile"

[env]
  # offload TLS on to fly-proxy;
  # tls-tls_options for [[services]] must be set
  TLS_OFFLOAD = "true"
  NODE_ENV = "production"
  CLOUD_PLATFORM = "fly"
  LOG_LEVEL = "info"

[experimental]
auto_rollback = true

# DNS over HTTPS (well, h2c and http1.1)
[[services]]
  internal_port = 8055
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true

  [services.concurrency]
  hard_limit = 575
  soft_limit = 500
  type = "connections"

  [[services.ports]]
  handlers = ["tls"]
  tls_options = { alpn = ["h2", "http/1.1"] }
  port = 443

  [[services.ports]]
  handlers = ["tls"]
  tls_options = { alpn = ["h2", "http/1.1"] }
  port = 8055

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "3s"
    grace_period = "15s"
    restart_limit = 3

# DNS over TCP/TLS
[[services]]
  internal_port = 10555
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true

  [services.concurrency]
  hard_limit = 575
  soft_limit = 500
  type = "connections"

  [[services.ports]]
  # TODO: ProxyProto v2
  handlers = ["tls"]
  port = 853

  [[services.ports]]
  # TODO: ProxyProto v2
  handlers = ["tls"]
  port = 10555

  [[services.tcp_checks]]
    interval = "30s"
    timeout = "3s"
    grace_period = "15s"
    restart_limit = 3

# community.fly.io/t/5490/3
[checks]
  [checks.up]
    # grace_period affects time taken for rolling deploys
    grace_period = "15s"
    interval = "15s"
    method = "get"
    path = "/check"
    port = 8888
    timeout = "3s"
    type = "http"

